baseUrl: http://localhost:9000
searchPath: /api/search
facetedSearchBaseUrl: http://localhost:9000/api
personsRootUrl: /domain/wwpersons
worksRootUrl: /domain/wwdocuments
VRE_ID: 'WomenWriters'

personTypeString: 'wwperson'
workTypeString: 'wwdocument'

userInfoPath: /api/system/users/me
userLoginUrl: https://secure.huygens.knaw.nl/saml2/login