baseUrl: http://test.resources.huygens.knaw.nl/womenwriters
facetedSearchBaseUrl: http://test.resources.huygens.knaw.nl/womenwriters/api
personsRootUrl: /domain/wwpersons
worksRootUrl: /domain/wwdocuments