baseUrl: http://test.resources.huygens.knaw.nl/womenwriters
searchPath: /api/search
facetedSearchBaseUrl: http://test.resources.huygens.knaw.nl/womenwriters/api
personsRootUrl: /domain/wwpersons
worksRootUrl: /domain/wwdocuments
VRE_ID: 'WomenWriters'

personTypeString: 'wwperson'
workTypeString: 'wwdocument'