baseUrl: http://localhost:9000
searchPath: /api/search
facetedSearchBaseUrl: http://localhost:9000/api
personsRootUrl: /domain/wwpersons
documentsRootUrl: /domain/wwdocuments
VRE_ID: 'WomenWriters'
relationTypeVariation: 'wwrelation'

personTypeString: 'wwperson'
documentTypeString: 'wwdocument'

userInfoPath: /api/system/users/me
userLoginUrl: https://secure.huygens.knaw.nl/saml2/login

resultRows: 25