baseUrl: http://resources.huygens.knaw.nl/womenwriters
searchPath: /api/search
facetedSearchBaseUrl: http://resources.huygens.knaw.nl/womenwriters/api
personsRootUrl: /domain/wwpersons
documentsRootUrl: /domain/wwdocuments
VRE_ID: 'WomenWriters'
relationTypeVariation: 'wwrelation'

educationPath: '/domain/wwkeywords?type=education'
financialSituationPath: '/domain/wwkeywords?type=financialSituation'
maritalStatusPath: '/domain/wwkeywords?type=maritalStatus'
professionPath: '/domain/wwkeywords?type=profession'
religionPath: '/domain/wwkeywords?type=religion'
socialClassPath: '/domain/wwkeywords?type=socialClass'

sourceCategoryPath: '/domain/keywords?type=docSourceType'

personTypeString: 'wwperson'
documentTypeString: 'wwdocument'

userInfoPath: /api/system/users/me
userLoginUrl: https://secure.huygens.knaw.nl/saml2/login

resultRows: 25